name: Build NATS-Based  REST API

on:
  push:
    branches: [master]

jobs:
  build_test: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Show the go version in use
        run: go version
      - name: Build the app
        run: |
            go mod download
            go build main.go
